% im = imresize(im2double(imread('TestNaturePhotography5.png')), [440, 660]);
  im = imresize(im2double(imread('../segmentation/Desert.png')), [600, 800]);
% im = im2double(imread('../../data/swimseg/images/0879.png'));
% im = im2double(imread('../segmentation/Luna.png'));

load('averageCloudHistVec.mat');
load('averageSkyHistVec.mat');
addpath('../segmentation/');
addpath('../replacement/');
%[pixelLabels, ~] = superpixels(im, 100);
[pixelLabels, ~, ~, Clusters] = slic(im, 400, 0.01, 0.05, 0.1, 3);
bw = boundarymask(pixelLabels);
[skyCloudPixelMask, pixelMask] = simpleClassifier(im, averageCloudHistVec, averageSkyHistVec, pixelLabels, Clusters);
replacedImage = inpaint(im, pixelMask, skyCloudPixelMask);
subplot(1,4,1);
imshow(im);
subplot(1,4,2);
imshow(imoverlay(im, bw, 'cyan'));
subplot(1,4,3);
imshow(imoverlay(skyCloudPixelMask / 2, bw, 'cyan'));
subplot(1,4,4);
imshow(replacedImage);